local DIR = "../../imgui/binding/src/generated"

local property_map = require("property_map")

local ImGuiTextBufferMember = property_map.Configuration()
    :setNamespace("imgui_binding_lua")
    :setClassName("ImGuiTextBufferMember")
    :setFunctionName("mapImGuiTextBufferMember")
    -- ImGuiTextBuffer
    :addClassMember("append" )
    :addClassMember("c_str"  )
    :addClassMember("clear"  )
    :addClassMember("empty"  )
    :addClassMember("reserve")
    :addClassMember("size"   )

property_map.build(ImGuiTextBufferMember, nil, DIR)

local ImGuiStyleMember = property_map.Configuration()
    :setNamespace("imgui_binding_lua")
    :setClassName("ImGuiStyleMember")
    :setFunctionName("mapImGuiStyleMember")
    -- ImGuiStyle
    :addClassMember("Alpha")
    :addClassMember("AntiAliasedFill")
    :addClassMember("AntiAliasedLines")
    :addClassMember("AntiAliasedLinesUseTex")
    :addClassMember("ButtonTextAlign")
    :addClassMember("CellPadding")
    :addClassMember("ChildBorderSize")
    :addClassMember("ChildRounding")
    :addClassMember("CircleTessellationMaxError")
    :addClassMember("ColorButtonPosition")
    :addClassMember("Colors")
    :addClassMember("ColumnsMinSpacing")
    :addClassMember("CurveTessellationTol")
    :addClassMember("DisabledAlpha")
    :addClassMember("DisplaySafeAreaPadding")
    :addClassMember("DisplayWindowPadding")
    :addClassMember("FrameBorderSize")
    :addClassMember("FramePadding")
    :addClassMember("FrameRounding")
    :addClassMember("GrabMinSize")
    :addClassMember("GrabRounding")
    :addClassMember("IndentSpacing")
    :addClassMember("ItemInnerSpacing")
    :addClassMember("ItemSpacing")
    :addClassMember("LogSliderDeadzone")
    :addClassMember("MouseCursorScale")
    :addClassMember("PopupBorderSize")
    :addClassMember("PopupRounding")
    :addClassMember("ScaleAllSizes")
    :addClassMember("ScrollbarRounding")
    :addClassMember("ScrollbarSize")
    :addClassMember("SelectableTextAlign")
    :addClassMember("TabBorderSize")
    :addClassMember("TabMinWidthForCloseButton")
    :addClassMember("TabRounding")
    :addClassMember("TabBarBorderSize")
    :addClassMember("TabBarOverlineSize")
    :addClassMember("TableAngledHeadersAngle")
    :addClassMember("TableAngledHeadersTextAlign")
    :addClassMember("TouchExtraPadding")
    :addClassMember("WindowBorderSize")
    :addClassMember("WindowMenuButtonPosition")
    :addClassMember("WindowMinSize")
    :addClassMember("WindowPadding")
    :addClassMember("WindowRounding")
    :addClassMember("WindowTitleAlign")
    :addClassMember("SeparatorTextBorderSize")
    :addClassMember("SeparatorTextAlign")
    :addClassMember("SeparatorTextPadding")
    -- ImGuiStyle Behaviors
    :addClassMember("HoverStationaryDelay")
    :addClassMember("HoverDelayShort")
    :addClassMember("HoverDelayNormal")
    :addClassMember("HoverFlagsForTooltipMouse")
    :addClassMember("HoverFlagsForTooltipNav")

property_map.build(ImGuiStyleMember, nil, DIR)
